import * as fs from "fs";
import * as path from "path";
import type { HardhatRuntimeEnvironment } from "hardhat/types";

export const frontendAbiDir = path.resolve(__dirname, "../../../web/src/lib/abi");
export const deploymentsDir = path.resolve(__dirname, "../../deployments");

const EXPORTED = ["Cluckr", "MockToken"] as const;

export type DeploymentRecord = {
  network: string;
  chainId: number;
  deployer: string;
  owner: string;
  house: string;
  token: string;
  cluckr: string;
  params: {
    edgeBps: number;
    burnBps: number;
    maxPayoutBps: number;
    revealTimeout: number;
    idleTimeout: number;
    minBet: string;
    maxBet: string;
  };
  fundedWei: string;
  deployedAt: string;
  txHash: string | null;
};

const NL = String.fromCharCode(10);

/**
 * Writes each exported contract's ABI to ../web/src/lib/abi/<Name>.json (for
 * the house, which imports JSON) and <Name>.ts (`as const`, so viem infers
 * every argument and return type in the front end).
 */
export async function exportAbis(hre: HardhatRuntimeEnvironment): Promise<void> {
  fs.mkdirSync(frontendAbiDir, { recursive: true });
  for (const name of EXPORTED) {
    const artifact = await hre.artifacts.readArtifact(name);
    const json = JSON.stringify(artifact.abi, null, 2);
    fs.writeFileSync(path.join(frontendAbiDir, `${name}.json`), json + NL);
    const exportName = `${name.charAt(0).toLowerCase()}${name.slice(1)}Abi`;
    const header = "// Generated by contracts/scripts/lib/exportAbi.ts on every compile. Do not edit.";
    fs.writeFileSync(path.join(frontendAbiDir, `${name}.ts`), `${header}${NL}export const ${exportName} = ${json} as const;${NL}`);
  }
}
